In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

Loading the Dataset


In [7]:
df = pd.read_csv("Reviews.csv", nrows=50000)

print(df.shape)
df.head()

(50000, 10)


,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...


Find Reviews Containing "light"

In [8]:
light_reviews = df[
    df["Text"].str.contains(r"\blight\b", case=False, na=False)
]

print("Total Reviews:", len(light_reviews))

Total Reviews: 1415


Display Some Reviews

In [9]:
for i, review in enumerate(light_reviews["Text"].head(30)):
    print(f"\nReview {i+1}")
    print(review)


Review 1
This is a confection that has been around a few centuries.  It is a light, pillowy citrus gelatin with nuts - in this case Filberts. And it is cut into tiny squares and then liberally coated with powdered sugar.  And it is a tiny mouthful of heaven.  Not too chewy, and very flavorful.  I highly recommend this yummy treat.  If you are familiar with the story of C.S. Lewis' "The Lion, The Witch, and The Wardrobe" - this is the treat that seduces Edmund into selling out his Brother and Sisters to the Witch.

Review 2
A very delicate green tea with a smooth light taste and an subtle floral tones and no bitter aftertaste.<br /><br />In the 20+ years we have been drinking Ahmad teas not even once have we been disappointed. The superb quality of Ahmad teas has remained consistent throughout the years.<br /><br />I am so happy to find Ahmad teas available here (thanks Amazon!) because only a few stores carry it in my area and they are quite a few miles away. The current deal for the 

Create Sentence List

In [10]:
sentences = [
    "This product is very light and easy on the stomach.",
    "Too much light entered the package.",
    "I enjoy this light and healthy snack."
]

Count Vectorization

In [11]:
vectorizer = CountVectorizer()

X = vectorizer.fit_transform(sentences)

dense_matrix = X.toarray()

print(dense_matrix)

[[1 1 0 0 0 1 1 0 1 0 1 0 1 1 1 0 1]
 [0 0 0 1 0 0 1 1 0 1 0 0 0 1 0 1 0]
 [1 0 1 0 1 0 1 0 0 0 0 1 0 0 1 0 0]]


Extract Vectors

In [12]:
vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

print(vec_1)
print(vec_2)
print(vec_3)

[1 1 0 0 0 1 1 0 1 0 1 0 1 1 1 0 1]
[0 0 0 1 0 0 1 1 0 1 0 0 0 1 0 1 0]
[1 0 1 0 1 0 1 0 0 0 0 1 0 0 1 0 0]


Dot Product Similarity

In [13]:
sim_1_2 = np.dot(vec_1, vec_2)

sim_1_3 = np.dot(vec_1, vec_3)

print("Sentence 1 vs Sentence 2 =", sim_1_2)
print("Sentence 1 vs Sentence 3 =", sim_1_3)

Sentence 1 vs Sentence 2 = 2
Sentence 1 vs Sentence 3 = 3
